[workspace]
authors = ["Xingxin HE <xingxin.he@connect.ust.hk>"]
channels = ["robostack-humble", "conda-forge"]
name = "pixi_ros2_sub"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[activation]

[activation.env]
ROS_DOMAIN_ID="110"
RMW_IMPLEMENTATION="rmw_cyclonedds_cpp"
CYCLONEDDS_URI="file://${PIXI_PROJECT_ROOT}/cyclonedds.xml"
ROS_NETWORK_INTERFACE="enxc8a362d29cec"
[tasks]
sub = "ros2 run demo_nodes_cpp listener"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-rmw-cyclonedds-cpp = ">=1.3.4,<2"
