[workspace]
authors = ["Xingxin HE <xingxin.he@connect.ust.hk>"]
channels = ["robostack-humble", "conda-forge"]
name = "pixi_ros2_sub"
platforms = ["linux-64"]
version = "0.1.0"

[activation]

[activation.env]
ROS_DOMAIN_ID="110"
RMW_IMPLEMENTATION="rmw_zenoh_cpp"
ZENOH_SESSION_CONFIG_URI="./config/zenoh_client.json5"

[tasks]
sub = "ros2 run demo_nodes_cpp listener"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-rmw-zenoh-cpp = ">=0.1.2,<0.2"
